name: tests_document
on: push

jobs:
  faire_test:
      runs-on: ubuntu-latest
      steps:
        - name: se deplacer dans le repertoire
          uses: actions/checkout@v3
        - name: setup java
          uses: actions/setup-java@v1
          with:
            java-version: 17
        - name: run test
          run: mvn test
